# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

genrule(
  name = "car_accident_275573",
  outs = ["car_accident_275573.txt"],
  cmd_bash = "echo hello world && echo hello world! >$@"
)

genrule(
  name = "eaten_sandwich_738682",
  outs = ["eaten_sandwich_738682.txt"],
  cmd_bash = "echo hello world && echo hello world! >$@"
)

string = """
***************
Confidential
***************

The basil was first discovered missing on 28th June 2022.
Two witnesses have came forward with relevant information.

Their names are Amy and Mark. Both witnesses have been interviewed.

"""
genrule(
  name = "missing_basil_089324",
  outs = ["missing_basil_123.txt"],
  cmd_bash = "echo '" + string + "' && echo '" + string + "'>$@"
)

genrule(
  name = "lost_dog_847941",
  outs = ["lost_dog_847941.txt"],
  cmd_bash = "echo hello world && echo hello world! >$@"
)
