# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

sh_binary(
  name = "454235",
  srcs = ["454235.sh"],
  deps = ["//people:amy"]
)

sh_binary(
  name = "565673",
  srcs = ["565673.sh"],
  deps = ["//people:mark"]
)
